default_stage:
  default_modifiers:
    GPTQModifier:
      targets: [Linear]
      ignore: [lm_head]
      scheme: W8A8
      block_size: 128
      dampening_frac: 0.01
      actorder: static
      offload_hessians: false
